apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-aglo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-aglo@sha256:f77a5af7dacfcb53cd4ea7fddedb2db5b52fd88da14f739b79388f06eed2560e
        name: my-nodejs
        resources: {}
status: {}
